name: Node.js CI

on: [ push ]

jobs:
  build-javascript:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: todomvc-webapp

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - run: npm run prettier:check
      - run: npm run build:storybook

  build-java:
    runs-on: ubuntu-latest
    needs: build-javascript

    strategy:
      matrix:
        java: [ 11, 15 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11, 15
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew build
      - run: ls todomvc-webapp
